@startuml

skinparam {
    legend {
        FontSize 20
        BackgroundColor SnowWhite
    }
    title {
    FontSize 30
    }
}
title Possible permutations of three numbers (3!) 
legend
    |= Stack |= Disorder|= Order       |= Operations        |
    | A | 0.000000      | (a < b) (b < c) | - ascending sorted |
    | B | 1.000000      | (a > b) (b > c) | (sa, rra) or (ra, sa)   |
    | C | 0.333333      | (a < b) (b > c) (a < c) | (rra, sa) or (sa, ra)   |
    | D | 0.666667      | (a < b) (b > c) (a > c) | rra                | |
    | E | 0.333333      | (a > b) (b < c) (a < c) | sa                 |
    | F | 0.666667      | (a > b) (b < c) (a > c)  | ra                 |
endlegend

stack stack {
node null as n1_null #white
node a as a #white
node b as b #white
node c as c #white
node null as n3_null #white
n1_null <-- a : prev
a <-- b : prev
a --> b : next
b <-- c : prev
b --> c : next
c --> n3_null : next
}


stack A {
node null as a1_null #white
node "1" as a1 #pink
node "2" as a2 #Violet
node "3" as a3 #salmon
node null as a3_null #white
a1_null <-- a1
a1 <-- a2 
a1 --> a2
a2 <-- a3
a2 --> a3
a3 --> a3_null
}

stack B {
node null as b1_null #white
node "3" as b1 #salmon
node "2" as b2 #Violet
node "1" as b3 #pink
node null as b3_null #white
b1_null <-- b1
b1 <-- b2
b1 --> b2
b2 <-- b3
b2 --> b3
b3 --> b3_null
}

stack C {
node null as c1_null #white
node "1" as c1 #pink
node "3" as c2 #salmon
node "2" as c3 #Violet
node null as c3_null #white
c1_null <-- c1
c1 <-- c2
c1 --> c2
c2 <-- c3
c2 --> c3
c3 --> c3_null
}

stack D {
node null as d1_null #white
node "2" as d1 #Violet
node "3" as d2 #salmon
node "1" as d3 #pink
node null as d3_null #white
d1_null <-- d1
d1 <-- d2
d1 --> d2
d2 <-- d3
d2 --> d3
d3 --> d3_null
}

stack E {
node null as e1_null #white
node "2" as e1 #Violet
node "1" as e2 #pink
node "3" as e3 #salmon
node null as e3_null #white
e1_null <-- e1
e1 <-- e2
e1 --> e2
e2 <-- e3
e2 --> e3
e3 --> e3_null
}

stack F {
node null as f1_null #white
node "3" as f1 #salmon
node "1" as f2 #pink
node "2" as f3 #Violet
node null as f3_null #white
f1_null <-- f1
f1 <-- f2
f1 --> f2
f2 <-- f3
f2 --> f3
f3 --> f3_null
}
