Skinparam {
ActivityDiamondBackgroundColor yellow;
ActivityDiamondFontSize 20;
ActivityFontSize 16;
BackgroundColor DeepSkyBlue;
ActivityBorderColor white;
ActivityBorderThickness 5;
ActivityDiamondBorderColor SnowWhite;
ArrowColor White;
ActivityStartColor white;
ActivityStopColor white;
ActivityColor white;

title {
    FontSize = 38
}
caption {
    FontSize = 22;
    FontColor Navy
}
}
caption © Martina Radkovičová - mradkovi@student.42prague.com | ft_push_swap 2026
@startuml
title ft_push_swap - main.c
start
if ((**arg_checker**(argc) == 1)) is (true) then 
        note: if (argc < 2) print error - no arguments
        :return (1);<<#Salmon>>
        stop
else (false)
    :has_flag = **validate_flag**(argv[1]);<<#Chartreuse>>
    note right: checks the first argument\nlooking for the flag -- "simple", "medium", "complex", or "adaptive"\nreturn:\n1 - flag found\n0 - flag not found\n-1 - invalid flag

    if (has_flag == -1) is (true) then
        :return (1);<<#Salmon>>
        note right: The program terminates if the invalid flag is found.
        stop
    else (false)
    :**create_empty_stack**(&stack_a);<<#Chartreuse>>
    :**create_empty_stack**(&stack_b);<<#Chartreuse>>
    if (**fill_stack_a**(&stack_a, argc, argv, has_flag) != 1) is (true) then
    note:Splits aruments in one array\nvalidates arguments (only numers, no duplicity)\nif argumnets are valid, fills the stack.
        :**clean_stack_memory**(&stack_a);<<#Salmon>>
        note right: error during stack filling - freed memory
        :return (write(2, "[ERROR]", 8), 1);<<#Salmon>>
        note right: print error\nprogram terminates
        stop
    else (false)
    if (has_flag == 1) is (true) then
        :**strategy_selector**(argv[1], &stack_a, &stack_b);<<#Chartreuse>>
        note right: Algorithm selection based on a flag
    else (false)
    :**adaptive_algorithm**(&stack_a, &stack_b);<<#Chartreuse>>
    note right: No flag is specified\nan adaptive algorithm is selected\nand choose the most suitable one.
    endif

     :**clean_stack_memory**(&stack_a);<<#Chartreuse>>
     note right: clear the memory before ending the program
stop
@enduml
