@startuml
start
skinparam {
ActivityBackgroundColor LightGreen;
ActivityDiamondBackgroundColor yellow;
ActivityFontSize 16;
ActivityBorderThickness 2
title {
FontSize 32
}
}
title "Algorithm for sorting four numbers"
partition "int minimum_index(t_stack *stack_a)" {
    :a = stack_a->top->value;
    :b = stack_a->top->next->value;
    :c = stack_a->bottom->prev->value;
    :d = stack_a->bottom->value;
    
    if ((a < b) && (a < c) && (a < d)) is (true) then
        :minimum_idx = 0;
    else if ((b < a) && (b < c) && (b < d)) is (true) then
        :minimum_idx = 1;
    else if ((c < a) && (c < b) && (c < d)) is (true) then
        :minimum_idx = 2;
    else
        :minimum_idx = 3;
    endif
    :return (minimum_idx);
    stop
}


partition "sort_four(t_stack *stack_a, t_stack *stack_b) {
if (stack_a == NULL || stack_b == NULL || stack_a->top == NULL)
    :return ; <<#salmon>>
    stop
endif

:minimum_idx = minimum_index(stack_a);
if (minimum_idx == 1) is (true) then
    :sa(stack_a);
else if (minimum_idx == 2) is (true) then
    :rra(stack_a);
    :rra(stack_a);
else if(minimum_idx == 3) is (true) then
    :rra(stack_a);
endif
if (compute_disorder(stack_a) > 0.000000) is (true) then
:pb(stack_a, stack_b);
:sort_three(stack_a);
:pa(stack_b, stack_a);
endif

stop
@enduml
