@startuml

title Stak operations

stack stack {
node NULL #white
node "first (top)" #LightBlue
node second #LightGreen
node n... #Orange
node "last (bottom)" #salmon
node " NULL" #white
NULL <-- "first (top)" : prev
"first (top)" --> second : next
"first (top)" <-- second : prev
second --> n... : next
second <-- n... : prev
n... --> "last (bottom)" : next
n... <-- "last (bottom)" : prev
"last (bottom)" --> " NULL" : next
}

stack "swap_stack\nbefore\t\tafter" {
node "   NULL" #white
node "(first) 5" #red
node "(second) 14" #yellow
node "(last) 8" #grey
node "NULL   " #white
"   NULL" <-- "(first) 5" : prev
"(first) 5" --> "(second) 14" : next
"(first) 5" <-- "(second) 14" : prev
"(second) 14" --> "(last) 8" : next
"(second) 14" <-- "(last) 8" : prev
"(last) 8" --> "NULL   " : next

node "   NULL " #white
node "14 (first)" #yellow
node "5 (second)" #red
node "8 (last)" #grey
node " NULL   " #white
"   NULL " <-- "14 (first)" : prev
"14 (first)" --> "5 (second)": next
"5 (second)" --> "14 (first)" : prev 
"5 (second)" --> "8 (last)" : next
"5 (second)" <-- "8 (last)" : prev
"8 (last)" --> " NULL   " : next
}

stack "rotate_stack\nbefore\t\tafter" {
node "(first) 6" #CornFlowerBlue
node "(second) 15" #pink
node "(last) 54" #Thistle
node "  NULL  " #white
node " NULL " #white
" NULL " <-- "(first) 6" : prev
"(first) 6" --> "(second) 15" : next
"(first) 6" <-- "(second) 15" : prev
"(second) 15" --> "(last) 54" : next
"(second) 15" <-- "(last) 54" : prev
"(last) 54" --> "  NULL  " : next
node "15 (first)" #pink
node "54 (second)" #Thistle
node "6 (last)" #CornFlowerBlue
node " NULL  " #white
node "  NULL " #white
" NULL  " <-- "15 (first)" : next
"15 (first)" --> "54 (second)" : next
"54 (second)" --> "15 (first)" : prev
"54 (second)" --> "6 (last)" : next
"6 (last)" -->"  NULL " : next
"54 (second)" <-- "6 (last)" : prev
}

stack "reverse_stack\nbefore\t\tafter" {
node "(first) 100" #gold
node "(second) 4" #magenta
node "(last) 42" #Cyan
node "   NULL  " #white
node " NULL    " #white
"   NULL  " <-- "(first) 100" : prev
"(first) 100" --> "(second) 4" : next
"(first) 100" <-- "(second) 4" : prev
"(second) 4" --> "(last) 42" : next
"(second) 4" <-- "(last) 42" : prev
"(last) 42" --> " NULL    " : next
node "   NULL    " #white
node "4 (last)" #magenta
node "100 (second)" #gold
node "42 (first)" #cyan
node "    NULL   " #white

"   NULL    " <-- "42 (first)" : prev
"42 (first)" --> "100 (second)" : next
"42 (first)" --> "100 (second)" : prev
"100 (second)" --> "4 (last)" : next
"4 (last)" <-- "100 (second)" : prev
"4 (last)" -->"    NULL   " : next

}

stack "push_stack\n\tsource_stack\t\t\t\t\tdest_stack / empty_dest" {
node "  NULL   " #white
node "(first) 1000" #DeepPink
node "(second) 357" #DeepSkyBlue
node "(last) 11" #Lime
node "    NULL  " #white

"  NULL   " <-- "(first) 1000" :prev
"(first) 1000" --> "(second) 357":next
"(first) 1000" <-- "(second) 357":prev
"(second) 357" --> "(last) 11" :next
"(second) 357" <-- "(last) 11" :prev
"(last) 11" --> "    NULL  " :next

node "    NULL    " #white
node "357 (first)" #DeepSkyBlue
node "11 (last)" #Lime
node "    NULL     " #white
"    NULL    " <-- "357 (first)" :prev
"357 (first)" --> "11 (last)" : next
"11 (last)" --> "357 (first)" : prev
"11 (last)" --> "    NULL     " : next

node "     NULL    " #white
node "1000 (first)" #DeepPink
node "750 (second)" #LightSteelBlue
node "2 (last)" #Bisque
node "    NULL      " #white
"     NULL    " <-- "1000 (first)" :prev
"1000 (first)" --> "750 (second)" : next
"750 (second)" --> "1000 (first)" : prev
"750 (second)" --> "2 (last)" : next
"2 (last)" --> "750 (second)" : prev
"2 (last)" --> "    NULL      " : next

node "  NULL    " #white
node "1000(first)" #DeepPink
node "    NULL" #white
"  NULL    " <-- "1000(first)" :prev
"1000(first)" --> "    NULL" : next
}
@enduml
